/* COLORS ---------------------------------------*/
#define 		COLOR_SERVER 			0x4169E1ff
#define 		COLOR_SUCCESS 			0x00FF7Fff
#define 		COLOR_ERROR 			0xFF4500ff
#define 		COLOR_WARNING			0xFFFF00ff
#define 		COLOR_VERMELHO			0xff0000ff
#define 		COLOR_AMARELO 			0xffff00ff
#define 		COLOR_WHITE				0xffffffff
#define         COLOR_GREEN             0x32CD32ff


/* COLORS EMBED ---------------------------------*/
#define 		EMBED_SERVER			"{4169E1}"
#define 		EMBED_SUCCESS			"{00FF7F}"
#define 		EMBED_ERROR				"{FF4500}"
#define 		EMBED_WARNING 			"{FFFF00}"
#define 		EMBED_VERMELHO			"{FF000}"	
#define 		EMBED_AMARELO			"{FFFF00}"
#define 		EMBED_WHITE				"{FFFFFF}"
#define 		EMBED_GREEN				"{32CD32}"

