#define 	DIALOG_START			1
#define 	DIALOG_REG_LOGIN 		2
#define 	DIALOG_REG_NICK 		3
#define 	DIALOG_REG_PASS 		4
#define 	DIALOG_REG_CONF_PASS 	5
#define 	DIALOG_REG_EMAIL 		6
#define 	DIALOG_REG_GEN	 		7
#define 	DIALOG_LOG_LOGIN		8
#define 	DIALOG_LOG_PASS			9
#define 	DIALOG_CONF_LOCATION	10
#define 	DIALOG_LOC_TITLE		11
#define 	DIALOG_LOC_INTS			12
#define 	DIALOG_LOC_EXIT			13
#define     DIALOG_LOC_MODIFY       14
#define     DIALOG_LOC_MOD_PCIKUP   15
#define     DIALOG_LOC_MOD_TITLE    16


#define 	DIALOG_DEBUG			10000
#define 	T_DEBUG					"{FFFFFF}Debug"