new bool:pScreenRegister[MAX_PLAYERS];
new bool:pScreenLogin[MAX_PLAYERS];
new bool:pScreenStart[MAX_PLAYERS];

// -> Variáveis de login --------------------------------------/
new timerSpawn[MAX_PLAYERS];
new logLogin[MAX_PLAYERS];
new logPass[MAX_PLAYERS];

// -> Variáveis de registro --------------------------------------/
new regLogin[MAX_PLAYERS];
new regNick[MAX_PLAYERS];
new regPass[MAX_PLAYERS];
new regConfPass[MAX_PLAYERS];
new regEmail[MAX_PLAYERS];
new regGen[MAX_PLAYERS];
new regCodePlayer[MAX_PLAYERS];